#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# +--- Options. --------------------------------------------------------------+
setopt nobeep                  # i hate beeps (on error)
setopt multios                 # pipe to multiple outputs
                               # echo "Hi!" > foo.txt > bar.txt
setopt autonamedirs            # use named dirs when possible
setopt rmstarwait              # 10 sec wait when deleting everything
setopt sharehistory            # killer: share history between multiple shells
