---
- name: install code snippets
  copy: src={{ item }}
        dest="~/Library/Application Support/Sublime Text 3/Packages/User/"
  with_fileglob:
    - "*.sublime-snippet"

- name: install user configurations
  copy: src=Preferences.sublime-settings
        dest="~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"

- name: install pyflakes linter
  pip: name=pyflakes state=present
