---
- name: update homebrew
  homebrew: update_homebrew=yes

- name: tap dupes
  homebrew_tap: tap=homebrew/dupes

- name: install CLI tools
  homebrew: name={{ item }} state=present
  with_items:
    - coreutils       # OSX defaults are outdated
    - tmux
    - tree
    - readline
    - wget
    - ack
    - bash
    - zsh
    - vim
    - git
    - ssh-copy-id
    - rsync
    - trash
    # - python
  when: ansible_os_family == 'Darwin'

- name: add convenience script
  copy: src=configure dest=/usr/local/bin/configure
