---
- name: tap dupes
  homebrew_tap: tap=homebrew/dupes

- name: install CLI tools
  homebrew: name={{ item }} state=present
  with_items:
    - tmux
    - tree
    - readline
    - wget
    - ack
    - bash
    - vim
    - git
    - ssh-copy-id
    - zsh
    - rsync
  when: ansible_os_family == 'Darwin'

- name: add convenience script
  copy: src=configure dest=/usr/local/bin/configure
