---
- name: install vim
  homebrew: name=vim state=present

- name: ensure target directory exists
  file: dest=~/.vim state=directory
  tags: vim

- name: clone Vundle
  git: repo=https://github.com/gmarik/vundle.git dest=~/.vim/bundle/vundle
  tags: vim

- name: copy vimrc file
  copy: src=vimrc dest=~/.vimrc
  tags: vim

- name: install plugins
  shell: vim --cmd 'set shortmess=at' +BundleInstall! +qall
  tags: vim
