---
- name: install GCC compiler | tap
  homebrew_tap: tap=homebrew/dupes state=present
  when: ansible_os_family == 'Darwin'

- name: install GCC compiler | install
  homebrew: name=apple-gcc42 state=present
  when: ansible_os_family == 'Darwin'

# - name: install ipython
#   pip: name={{ item }} state=present
#   with_items:
#     - ipython
#     - ipdb
