---
- name: install GCC compiler | tap
  homebrew_tap: tap=homebrew/dupes state=present
  when: ansible_os_family == 'Darwin'

- name: install GCC compiler | install
  homebrew: name=apple-gcc42 state=present
  when: ansible_os_family == 'Darwin'

- name: install git up
  pip: name={{ item }} state=latest
  with_items:
    - git-up
