---
- name: ensure target dir
  file: path="~/.ansible/fonts" state=directory

- name: download Source Code Pro
  get_url: url=https://github.com/adobe-fonts/source-code-pro/archive/1.017R.zip
           dest="~/.ansible/fonts/source-code-pro-1.017R.zip"

- name: extract Source Code Pro
  unarchive: src="~/.ansible/fonts/source-code-pro-1.017R.zip" dest="~/.ansible/fonts/"

- name: install Source Code Pro
  copy: src={{ item }} dest="~/Library/Fonts/"
  with_fileglob: "~/.ansible/fonts/source-code-pro-1.017R/OTF/*"

- name: install Inconsolata Regular
  get_url: url=https://googlefontdirectory.googlecode.com/hg/ofl/inconsolata/Inconsolata-Regular.ttf
           dest="~/Library/Fonts/Inconsolata-Regular.ttf"

- name: install Inconsolata Bold
  get_url: url=https://googlefontdirectory.googlecode.com/hg/ofl/inconsolata/Inconsolata-Bold.ttf
           dest="~/Library/Fonts/Inconsolata-Bold.ttf"

- name: download Roboto
  get_url: url=http://developer.android.com/downloads/design/roboto-1.2.zip
           dest="~/.ansible/fonts/roboto.zip"

- name: extract Roboto
  unarchive: src=~/.ansible/fonts/roboto.zip dest=~/.ansible/fonts/

- name: install Roboto
  copy: src={{ item }} dest="~/Library/Fonts/"
  with_fileglob: "~/.ansible/fonts/Roboto_v1.2/Roboto/*.ttf"

- name: install Tesla
  get_url: url=https://dl.dropboxusercontent.com/u/112722970/TESLA.ttf
           dest="~/Library/Fonts/TESLA.ttf"
